# Site
title: ReverseLivingTech
description: ReverseLivingTech Introduction
baseurl: /ReverseLivingTech.github.io
permalink: /:title

# Repository
git:
  repository_url: https://github.com/ReverseLivingTech/ReverseLivingTech.github.io

# Navigation
nav:
  Project:
    - text: Home
      url: /
      available: true
    - text: About
      url: /about
      available: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md"]
